<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Title_css-tlfecz-indicatorContainer</name>
   <tag></tag>
   <elementGuidId>9d4133f1-59ef-4cff-a990-db0d4fc1a6c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selectOne']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-tlfecz-indicatorContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-tlfecz-indicatorContainer >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36c94263-6d0c-4847-8239-c4373b92b856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a7c9683-5b82-45a5-8a67-b6e7e5908658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-tlfecz-indicatorContainer</value>
      <webElementGuid>d047997c-da28-4aa7-b69a-6257d19fb32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOne&quot;)/div[@class=&quot;css-yk16xz-control&quot;]/div[@class=&quot;css-1wy0on6&quot;]/div[@class=&quot;css-tlfecz-indicatorContainer&quot;]</value>
      <webElementGuid>3cdcc2bb-174e-4d82-aa1b-ef8bb2ff6b20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectOne']/div/div[2]/div</value>
      <webElementGuid>bf721bb5-40f9-45e7-bc4a-c06cc1021306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Title'])[1]/following::div[5]</value>
      <webElementGuid>e252b30e-949b-4c7d-a6ca-3d4affbb343f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select One'])[1]/following::div[11]</value>
      <webElementGuid>a29450bc-08b9-431d-82d7-1e5680adaf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old Style Select Menu'])[1]/preceding::div[1]</value>
      <webElementGuid>9fa20549-cee7-42f9-878a-d07b1282b75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiselect drop down'])[1]/preceding::div[6]</value>
      <webElementGuid>5a2446c3-f464-4d16-ac2d-24b6ffe08ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div</value>
      <webElementGuid>73b23ef2-611e-44a6-ae34-8e7befdb011b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
