<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hover me to see_toolTipTextField</name>
   <tag></tag>
   <elementGuidId>b43c69aa-1915-450c-aa47-3478c872f1d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toolTipTextField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='toolTipTextField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Hover me to see&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43695923-ad8d-4536-a47b-b6b820a845de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bfbbbd40-72c0-4b81-ae26-9d7c39593e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hover me to see</value>
      <webElementGuid>63ce0edc-c044-44ea-b41b-539de215b2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74308079-d5c8-4aa3-b05b-251d00f2fa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toolTipTextField</value>
      <webElementGuid>9bfdcbee-1e2c-49d9-976a-89659cf0447c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> mr-sm-2 form-control</value>
      <webElementGuid>5e50bd07-966b-4a58-a8df-c461ec0eae62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>textFieldToolTip</value>
      <webElementGuid>c80c6722-91f6-461d-85e0-a432f8aeefc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toolTipTextField&quot;)</value>
      <webElementGuid>818e33af-3c9a-484a-9124-f9070702d4b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='toolTipTextField']</value>
      <webElementGuid>a9f61fb4-a122-45d2-8e06-724f4d32bb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='texFieldToolTopContainer']/input</value>
      <webElementGuid>3b7eccae-8542-43e3-8496-10082ed77e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>17bf93ef-d266-41c0-ae23-4e304b0a6644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Hover me to see' and @type = 'text' and @id = 'toolTipTextField']</value>
      <webElementGuid>4663f86c-4d41-4418-bf9e-1751ef591827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
