<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-uyp0r54caxbr</name>
   <tag></tag>
   <elementGuidId>53c5eb7a-b762-4da7-809a-4dec0c7ff602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-uyp0r54caxbr&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-uyp0r54caxbr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-uyp0r54caxbr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>472e9f15-1e7b-4c61-ba43-f4b0a2777499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>5cf19b9a-fb6e-4c22-9d90-2362012a61a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ae690f37-a5b3-4ea9-a625-209241c8011f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>581148dc-df08-4c86-add7-265d93f782b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>192d6fef-8638-4553-827d-6826b23a606d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-uyp0r54caxbr</value>
      <webElementGuid>c6ff1c4f-91ff-4529-90f3-e21f296690b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e62fcf3-29dc-48db-9613-76013079fe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>54a4dd10-6378-4852-8b83-ceca7d677fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>2591f596-79aa-4804-adc8-fbbb59f52f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7&amp;co=aHR0cHM6Ly9kZW1vcWEuY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=7gg7H51Q-naNfhmCP3_R47ho&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=30000&amp;cb=ih67zswrj78r</value>
      <webElementGuid>600f0a62-3784-41f7-9fa9-887e51f47a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>b878769e-3ded-4a67-a8e9-41b9cc81b610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-uyp0r54caxbr']</value>
      <webElementGuid>bee60358-2587-48fe-8b7b-c6996461ca25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>ca795b6b-d2bb-4b4d-9ed7-f9dd05eebf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/iframe</value>
      <webElementGuid>bdce7bd8-07c7-4bbc-b0fb-b6aa9ffaa2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-uyp0r54caxbr' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdsKacZAAAAAIxY1X8GuHZljebmKWs8JGp97UK7&amp;co=aHR0cHM6Ly9kZW1vcWEuY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=7gg7H51Q-naNfhmCP3_R47ho&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=30000&amp;cb=ih67zswrj78r']</value>
      <webElementGuid>6b6c9b29-1884-4f02-bbe3-db8bce48f80c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
