<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I will always stick to the center</name>
   <tag></tag>
   <elementGuidId>d8723b42-64ea-485a-a477-dc3b0fbb1e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cursorCenter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cursorCenter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;I will always stick to the center&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48c446b6-9c5d-41f4-824d-f041798f041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursorCenter</value>
      <webElementGuid>a054d2c5-4b05-41c9-9a56-a40ed808da92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box ui-draggable ui-draggable-handle</value>
      <webElementGuid>05c1610f-2be1-4ce0-a8f4-d6e17f0fc5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I will always stick to the center</value>
      <webElementGuid>827a5c4b-bc2f-45f9-8a44-38d10926e2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursorCenter&quot;)</value>
      <webElementGuid>5fcaf8cb-52f2-481e-9dd8-13aba6f896c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cursorCenter']</value>
      <webElementGuid>6e805517-a835-4b37-a5f2-079ad64bc26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-cursorStyle']/div/div</value>
      <webElementGuid>4295d896-f7d4-4f66-add7-6a2c665ba11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My cursor is at top left'])[1]/preceding::div[1]</value>
      <webElementGuid>94f1e2a8-7ccc-49b7-9c6f-900c21193006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My cursor is at bottom'])[1]/preceding::div[2]</value>
      <webElementGuid>3629740b-660e-464d-bd94-daa86475cc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I will always stick to the center']/parent::*</value>
      <webElementGuid>96f5c5cf-4d9f-44ca-ad6d-15c9749c2d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>669e051b-df22-4b6e-8c11-3bb5f84fa126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cursorCenter' and (text() = 'I will always stick to the center' or . = 'I will always stick to the center')]</value>
      <webElementGuid>3b91fe32-8fa8-4cc9-867b-a5df8724d3a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
