<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Only X</name>
   <tag></tag>
   <elementGuidId>52c115e5-8b40-4a22-8bcc-3d91a98b334b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#restrictedX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='restrictedX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Only X&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b177beb3-7a7f-46d0-848d-675f92fd9b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restrictedX</value>
      <webElementGuid>49ee3c8d-bdb3-47f7-8f9f-42c1c15c73c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box ui-draggable ui-draggable-handle</value>
      <webElementGuid>678e7ad7-1514-4c13-82d0-226e96d0b63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only X</value>
      <webElementGuid>bdc0f767-bad4-4ab2-af8c-2ba95e93bbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restrictedX&quot;)</value>
      <webElementGuid>7f52a072-edbd-404f-9e50-bc2640b6ecb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='restrictedX']</value>
      <webElementGuid>a058d0b4-0c52-4309-a22e-198627a5a1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-axisRestriction']/div/div</value>
      <webElementGuid>601300e9-8898-4bee-b5c8-e0259b347f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/following::div[3]</value>
      <webElementGuid>0ab82ae4-498f-4eb3-ba27-729feaafcaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dragabble'])[2]/following::div[6]</value>
      <webElementGuid>98f18685-4ed5-4011-8f0c-39d3ea0e740f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only Y'])[1]/preceding::div[1]</value>
      <webElementGuid>9af50a00-74b5-4126-8b75-b3df2efd29e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Only X']/parent::*</value>
      <webElementGuid>103a4f4c-1e77-4c60-83dd-647b4b0a219e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>b325e104-e374-4f5d-9b51-7b54063386a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'restrictedX' and (text() = 'Only X' or . = 'Only X')]</value>
      <webElementGuid>06b9d306-3fe7-47f2-acca-c2af4cc6c3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
