<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Acceptable</name>
   <tag></tag>
   <elementGuidId>0ca8ed7e-dee8-4dd0-a841-3e443283f3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acceptable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Acceptable&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1cb29fa4-902a-4468-a86b-4a482a38a262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptable</value>
      <webElementGuid>d2ae6438-54b1-4a3f-beef-9147130ff53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box mt-4 ui-draggable ui-draggable-handle</value>
      <webElementGuid>2cf6280c-3bcd-4022-8b24-b4f256437451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acceptable</value>
      <webElementGuid>31dc1300-946e-44af-952d-27afa683c731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptable&quot;)</value>
      <webElementGuid>65ec4a3b-5916-447e-a612-ec39a72c9856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='acceptable']</value>
      <webElementGuid>acb68b5c-b81a-45a4-a8d9-ff1106f43f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acceptDropContainer']/div/div</value>
      <webElementGuid>eac9b12b-2625-4293-9961-df55d42b53e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/following::div[5]</value>
      <webElementGuid>bd87e6a4-5a6a-455f-ae2b-762dc8af72d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Droppable'])[2]/following::div[9]</value>
      <webElementGuid>f4813637-416a-45be-8c7e-4f011302aed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag Me'])[1]/preceding::div[3]</value>
      <webElementGuid>2937815a-50a4-4acd-b3d2-92bf5ca5eff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acceptable']/parent::*</value>
      <webElementGuid>3d825ee5-a651-41ba-863c-1d43d8d91b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>2088a8d5-7ac7-41a4-9b6e-ef35cd82a57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'acceptable' and (text() = 'Acceptable' or . = 'Acceptable')]</value>
      <webElementGuid>5e8c0116-3f19-442b-9572-5af89256d3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
