<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OneTwoThreeFourFiveSixSevenEightNine</name>
   <tag></tag>
   <elementGuidId>8ee84bc1-4447-49d9-a282-857d989b4782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.create-grid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-tabpane-grid']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;OneTwoThreeFourFiveSixSevenEightNine&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f5bc829-d8b3-4075-bb21-db854642517e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create-grid</value>
      <webElementGuid>628ca357-fe5a-49aa-8bc1-0ae8b07ffb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OneTwoThreeFourFiveSixSevenEightNine</value>
      <webElementGuid>85594600-d9b3-4771-bd5a-fe614173d3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-tabpane-grid&quot;)/div[@class=&quot;grid-container mt-4&quot;]/div[@class=&quot;create-grid&quot;]</value>
      <webElementGuid>eb1ee668-4def-401a-ba9b-3294be70eb85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-tabpane-grid']/div/div</value>
      <webElementGuid>e2521a9b-0488-4321-a999-d8789718f7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Six'])[1]/following::div[3]</value>
      <webElementGuid>cc2e2082-aeec-4754-9833-92cbec61ae99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Five'])[1]/following::div[4]</value>
      <webElementGuid>409c2602-1d29-4576-bbfa-27560d74cd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>9e0b8cfd-cfd5-4257-b4c1-b628ebc577a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OneTwoThreeFourFiveSixSevenEightNine' or . = 'OneTwoThreeFourFiveSixSevenEightNine')]</value>
      <webElementGuid>7a5bfc34-3128-45cd-a9fa-6af7f1240e5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
