<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My cursor is at bottom</name>
   <tag></tag>
   <elementGuidId>01fef882-ccb0-41f6-9086-00acd303eb3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cursorBottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cursorBottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cursorBottom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>636107ef-178a-4fb2-9568-442a6de631da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursorBottom</value>
      <webElementGuid>a47e01dc-176c-4a3e-984a-f04df955af70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box ui-draggable ui-draggable-handle</value>
      <webElementGuid>f6f41ff5-60ff-4528-9dd2-bd65918b7d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My cursor is at bottom</value>
      <webElementGuid>8464f41d-5638-4d1c-bdbf-bb550b8f33f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursorBottom&quot;)</value>
      <webElementGuid>d559c899-37ea-4280-b2d1-85fba6657ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cursorBottom']</value>
      <webElementGuid>bd480667-8c73-46e0-867b-7c4b132c9913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-cursorStyle']/div/div[3]</value>
      <webElementGuid>ba428cc3-a52d-4996-aefd-5cd3d210b671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My cursor is at top left'])[1]/following::div[1]</value>
      <webElementGuid>cd677f77-5b7f-448a-bde4-950a689a781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I will always stick to the center'])[1]/following::div[2]</value>
      <webElementGuid>c4a8fac4-073c-4dad-8be6-0abab2988017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[13]</value>
      <webElementGuid>dd9c40c0-74b8-43d0-a089-2ac2c5126333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>eab707ff-a9af-4d29-82ce-1bfb11eedf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cursorBottom' and (text() = 'My cursor is at bottom' or . = 'My cursor is at bottom')]</value>
      <webElementGuid>782a8b2f-a6b3-45f1-9926-d6247abae50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
