<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag meDropped</name>
   <tag></tag>
   <elementGuidId>402995a6-c3b9-48bd-bcd9-9ce536e4b3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simpleDropContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='simpleDropContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Drag meDropped!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aac5087f-f5bc-401b-bf47-413e1382dab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>simple-drop-container</value>
      <webElementGuid>9903b9e9-c072-4138-955f-f211580336af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simpleDropContainer</value>
      <webElementGuid>f8ec35d9-ff22-4664-9499-15c323096d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag meDropped!</value>
      <webElementGuid>b6e1fd1b-a865-4322-a053-ebc80c6a4b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simpleDropContainer&quot;)</value>
      <webElementGuid>a9c3b034-ff7b-4c2d-8d1f-7bcfdffe31e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='simpleDropContainer']</value>
      <webElementGuid>742f35a9-118c-4757-8c10-615bda09594f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='droppableExample-tabpane-simple']/div</value>
      <webElementGuid>390cb862-06ec-4c7f-9025-a888f0c257d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Droppable'])[2]/following::div[3]</value>
      <webElementGuid>1471d6d7-7be0-49de-b517-d40e14b763a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[7]</value>
      <webElementGuid>571f56d4-4ebf-4df6-afc8-c5ee5f67cf1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acceptable'])[1]/preceding::div[3]</value>
      <webElementGuid>5215782f-3b59-4d13-af59-92f3aff2a721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>4ffc0c60-5f09-43d5-9eea-b64d9d6dedc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'simpleDropContainer' and (text() = 'Drag meDropped!' or . = 'Drag meDropped!')]</value>
      <webElementGuid>7b57ca84-1346-4319-8ee7-bbbda8d7ad54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
