<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Im contained within the box_1</name>
   <tag></tag>
   <elementGuidId>e5293fc6-3022-469e-9042-0274ff95b968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#containmentWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='containmentWrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#containmentWrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4abd4ad2-fa34-4b81-ac0f-3b0616f35b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>containmentWrapper</value>
      <webElementGuid>d59e7389-d285-4527-9367-5d83f18c071c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>containment-wrapper m-4</value>
      <webElementGuid>ec2a4e92-d86c-4ab8-8c0b-69bbaf63e18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I'm contained within the box</value>
      <webElementGuid>54e9d342-07ba-46f4-a498-3e379322b616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containmentWrapper&quot;)</value>
      <webElementGuid>9d5a27d3-22ce-4a7c-863f-a2e2fb45268f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='containmentWrapper']</value>
      <webElementGuid>2008754c-796d-4dcf-bb62-ae022070016b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-containerRestriction']/div</value>
      <webElementGuid>876ab4a2-c30e-4afd-a16b-9373e9f406db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only Y'])[1]/following::div[2]</value>
      <webElementGuid>88ebcf07-a5df-49d9-b858-e7743ef25f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only X'])[1]/following::div[3]</value>
      <webElementGuid>e71613c4-7faf-4cfb-a53d-e7ed1699f328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div</value>
      <webElementGuid>e15f21e2-62be-4ea3-8ef7-44d688172853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'containmentWrapper' and (text() = concat(&quot;I&quot; , &quot;'&quot; , &quot;m contained within the box&quot;) or . = concat(&quot;I&quot; , &quot;'&quot; , &quot;m contained within the box&quot;))]</value>
      <webElementGuid>927a880a-44dd-4cff-9400-d3b770c54a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
