<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Resizable box, starting at 200x200. Min_a395c9_1</name>
   <tag></tag>
   <elementGuidId>d3a6cbe2-f6dc-4932-8b52-eb9cc9b9d84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.constraint-area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Resizable box, starting at 200x200\. Min size is 150x150, max is 500x300\.$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>954dcbbc-94e2-439b-aeb0-6b03c661a3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>constraint-area</value>
      <webElementGuid>6702e169-2120-4eaa-acfa-5852f7459b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resizable box, starting at 200x200. Min size is 150x150, max is 500x300.</value>
      <webElementGuid>1566b173-aa4d-49b2-aaa4-73ba89cc15b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;container playgound-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mt-4 col-md-6&quot;]/div[@class=&quot;resizable-container&quot;]/div[@class=&quot;constraint-area&quot;]</value>
      <webElementGuid>3244eec1-7a80-453f-83d4-a6702ff7771a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>5baec8d5-d60c-467a-ad3d-98d5142185da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resizable'])[2]/following::div[1]</value>
      <webElementGuid>5da8d4d6-71c1-4d99-b78d-90a4c1f07ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[5]</value>
      <webElementGuid>9abdaabe-5bad-47ca-b0e5-f3c08f1a594e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resizable'])[3]/preceding::div[3]</value>
      <webElementGuid>f7ed7eb3-2303-450d-a8d1-98909e423c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>1ebbeade-b35a-4076-b196-59a10dbdeed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Resizable box, starting at 200x200. Min size is 150x150, max is 500x300.' or . = 'Resizable box, starting at 200x200. Min size is 150x150, max is 500x300.')]</value>
      <webElementGuid>52a2f696-f70f-4422-b80b-9085242330aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
