<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag meDrop here</name>
   <tag></tag>
   <elementGuidId>acb335ab-a00c-4018-a1ff-793db31881e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simpleDropContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='simpleDropContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Drag meDrop here&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e700f84f-8dc7-43b1-98cb-ae2d066dc2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>simple-drop-container</value>
      <webElementGuid>cbdeec00-b7aa-494c-86ac-482e4c76fc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simpleDropContainer</value>
      <webElementGuid>4f68bac4-2c29-40ac-82f4-d4ae3536f53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag meDrop here</value>
      <webElementGuid>49b6ad92-e856-4848-b195-e74fa27e56a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simpleDropContainer&quot;)</value>
      <webElementGuid>57fd8ec3-cc63-4bc1-8b68-1794dd8961c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='simpleDropContainer']</value>
      <webElementGuid>1683a6f8-2e2e-4d34-9d3e-92f612fe8c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='droppableExample-tabpane-simple']/div</value>
      <webElementGuid>d5f9d08b-41c3-4c77-8efd-96a4ec76bca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Droppable'])[2]/following::div[3]</value>
      <webElementGuid>f7fe4f70-7669-4baa-b7a7-b8792c705fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[7]</value>
      <webElementGuid>b1a5722f-d903-4cba-b255-82ca416a98e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acceptable'])[1]/preceding::div[3]</value>
      <webElementGuid>3c91f1d5-997c-4c0e-9736-8ad2cd8b8864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>25cc067b-4238-4b92-8dea-192344185d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'simpleDropContainer' and (text() = 'Drag meDrop here' or . = 'Drag meDrop here')]</value>
      <webElementGuid>bce223b5-faad-413a-9d6a-93581ba63edd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
