<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Seven</name>
   <tag></tag>
   <elementGuidId>c92df2e6-c478-44d5-88a1-ccb2aec3a429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#row3 > li.list-group-item.list-group-item-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row3']/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Seven&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6cdc7a68-1d37-4f86-a842-9af1d76468c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action</value>
      <webElementGuid>9870fb13-f016-4f70-bff9-99289250ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seven</value>
      <webElementGuid>afe28e53-4f00-450f-aab7-04afb015c385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row3&quot;)/li[@class=&quot;list-group-item list-group-item-action&quot;]</value>
      <webElementGuid>5304f69d-8608-4eff-b104-5cd57c965d9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row3']/li</value>
      <webElementGuid>704c1bbc-5c21-492a-86eb-a2b695c91d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Six'])[1]/following::li[1]</value>
      <webElementGuid>f3c793e5-fa43-49bb-9262-f34d01f8a218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Five'])[1]/following::li[2]</value>
      <webElementGuid>01e391a6-a17b-4c57-99dd-593b3a59b9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eight'])[1]/preceding::li[1]</value>
      <webElementGuid>5a81a1c5-0398-4732-b8cc-6f471be92236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nine'])[1]/preceding::li[2]</value>
      <webElementGuid>0faca8d3-dc96-42bd-9c5f-010cb1482279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seven']/parent::*</value>
      <webElementGuid>be9da84e-a05b-47a0-907d-954b85050784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li</value>
      <webElementGuid>42303f58-df3b-4722-a85c-31db4d81492d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Seven' or . = 'Seven')]</value>
      <webElementGuid>d83fcce0-e55c-4d33-af93-02ca451f7a76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
